### ISSUE TITLE
Dockerfile not found

### ISSUE THREAD

**Issue by texdade** [gonuit/heroku-docker-deploy#17]
Hi!

I just set up a workflow using this action, but it fails as it cannot find the Dockerfile. The error log is:

> Error: File: "Dockerfile" does not exist.

but the Dockerfile is in the root of my project. This is how I set up the action:

```
name: Heroku container deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          process_type: web     
```

In case it's needed, [the repo is public](https://github.com/texdade/LeagueOfScrapers)
