### ISSUE TITLE
Build options such as --build-arg fails

### ISSUE THREAD

**Issue by aminpaks** [gonuit/heroku-docker-deploy#18]
Hi there,

Thanks for your Github Actions and work.
I tried to use it on our project and it seems it fails when we pass `--build-arg VALUE="key"` in options.

I didn't try but from having a look the source seems to be fine, will you be able to verify this?

Here is the failure we get:
```
Run gonuit/heroku-docker-deploy@v1.3.3
Logging into the Heroku docker registry...
Building docker container...
  "docker build" requires exactly 1 argument.
  See 'docker build --help'.
  
  Usage:  docker build [OPTIONS] PATH | URL | -
  
  Build an image from a Dockerfile
Error: Building container failed.
Error: undefined
```

here is a sample of what we're using and it fails:
```yml
  deploy-integration:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy (Build, Push & Release)
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_LOGIN }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: deno-fireplace
          dockerfile_directory: .
          docker_options: '--build-arg key="${{ secrets.SECRET_KEY }}" --build-arg commit_hash="${{ github.sha }}"'

```

**Comment by aminpaks** [comment]
Never mind it's working! Don't know how I missed the version

**Comment by matias-gonz** [comment]
Hello, it is not working for me, what did you change from that so that it would work?

**Comment by aminpaks** [comment]
@matias-gonz just use pure Github Actions run and it should work. I didn't know that the runner even supports Heroku command like. This is what I'm doing right now it works fine:
```yml
name: Test & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy-development:
    runs-on: ubuntu-latest
    name: Deploy to Development
    needs: test
    env:
      HEROKU_APP_NAME: aminpaks
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Image
        run: |
          echo $HEROKU_API_KEY | docker login -u ${{ secrets.HEROKU_LOGIN }} registry.heroku.com --password-stdin
          docker build --build-arg commit_hash=${{ github.sha }} --tag registry.heroku.com/${HEROKU_APP_NAME}/web .
          docker push registry.heroku.com/${HEROKU_APP_NAME}/web
          heroku container:release web --app ${HEROKU_APP_NAME}

```
